In [1]:
%pylab inline
import numpy as np
import pandas as pd
import os
from scipy.stats import binned_statistic_2d

Populating the interactive namespace from numpy and matplotlib

In [2]:
# загрузка майских значений и регионов:
os.chdir('D:\\TAXI_all_files') # перенес данные на другой диск раб. компьютера
may_2016 = pd.read_csv('yellow_tripdata_2016-06.csv', low_memory=False)

os.chdir('C:\\Users\\rosas\\OneDrive\\Документы\\JUPYTER\\TAXI') # возврат в рабочую директорию

In [3]:
#may_2016

In [4]:
#may_2016.info()

In [5]:
regions = pd.read_csv('regions.csv', delimiter=';')

In [6]:
indexNames = may_2016[(may_2016['trip_distance'] == 0) | (may_2016['passenger_count'] == 0)
                      | (may_2016['pickup_longitude'] < -74.25559) | (may_2016['pickup_longitude'] > -73.70001) 
                      | (may_2016['pickup_latitude'] < 40.49612) | (may_2016['pickup_latitude'] > 40.91553)].index
may_2016.drop(indexNames , inplace=True)

In [7]:
may_2016[['tpep_pickup_datetime', 'tpep_dropoff_datetime']] = may_2016[['tpep_pickup_datetime', 'tpep_dropoff_datetime']].apply(pd.to_datetime)
may_2016['delta_tpep_datetime'] = may_2016['tpep_dropoff_datetime'] - may_2016['tpep_pickup_datetime']

In [8]:
indexNames = may_2016[(may_2016['delta_tpep_datetime'] <= '00:00:00')].index
may_2016.drop(indexNames , inplace=True)

In [9]:
may_2016['tpep_pickup_datetime'] = may_2016['tpep_pickup_datetime'].dt.floor("H")

In [10]:
range_1 = [[-74.25559, -73.70001], [40.49612, 40.91553]]

In [11]:
ret = binned_statistic_2d(may_2016['pickup_longitude'], may_2016['pickup_latitude'], may_2016.VendorID, 'count', bins=[50, 50], expand_binnumbers=True, range=range_1)

In [12]:
may_2016['region'] = (ret[3][0] - 1) * 50 + ret[3][1]

In [13]:
# Агрегированные данные за май 2016 года по часам (по горизонтали) и областям (по вертикали)
aggr = may_2016.pivot_table(index='region', columns='tpep_pickup_datetime', values='RatecodeID', aggfunc='count', dropna=True, fill_value=0)

In [14]:
# Запись данных для 2ой недели работы:
os.chdir('D:\\TAXI_all_files\\AGG')

aggr.to_csv('july_2016_aggr.csv')

os.chdir('C:\\Users\\rosas\\OneDrive\\Документы\\JUPYTER\\TAXI')

In [15]:
aggr[:14]

tpep_pickup_datetime,2016-06-01 00:00:00,2016-06-01 01:00:00,2016-06-01 02:00:00,2016-06-01 03:00:00,2016-06-01 04:00:00,2016-06-01 05:00:00,2016-06-01 06:00:00,2016-06-01 07:00:00,2016-06-01 08:00:00,2016-06-01 09:00:00,...,2016-06-30 14:00:00,2016-06-30 15:00:00,2016-06-30 16:00:00,2016-06-30 17:00:00,2016-06-30 18:00:00,2016-06-30 19:00:00,2016-06-30 20:00:00,2016-06-30 21:00:00,2016-06-30 22:00:00,2016-06-30 23:00:00
region,,,,,,,,,,,,,,,,,,,,,
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
49,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
61,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
77,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0